# -*- coding: utf-8 -*-
"""week 7 assignment 5 annie fu.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D9NHjU7vIlPfnIxt7pzz5V8WLM9pape5

# MCP Server Setup
"""

# Install required packages
!pip install flask flask-cors requests termcolor pyngrok -q

"""### Database Setup"""

!python database_setup.py

import sqlite3

conn = sqlite3.connect("/content/support.db")
cur = conn.cursor()

cur.execute("SELECT * FROM customers;")
print(cur.fetchall())

import sqlite3
import pandas as pd

conn = sqlite3.connect("/content/support.db")

df = pd.read_sql_query("SELECT * FROM customers;", conn)
df

import sqlite3

conn = sqlite3.connect("/content/support.db")
cur = conn.cursor()

cur.execute("SELECT * FROM tickets;")
print(cur.fetchall())

import sqlite3
import pandas as pd

conn = sqlite3.connect("/content/support.db")

df = pd.read_sql_query("SELECT * FROM tickets;", conn)
df

"""###Save the DB tools as mcp_tools.py"""

import sqlite3
from typing import Optional, Dict, List, Any

DB_PATH = "/content/support.db"

def get_db_connection():
    """Create a database connection with row factory for dict-like access."""
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    return conn

def row_to_dict(row: sqlite3.Row) -> Dict[str, Any]:
    """Convert SQLite row to dictionary."""
    return {key: row[key] for key in row.keys()}


# ============================================================
# REQUIRED MCP TOOL 1 — GET CUSTOMER
# ============================================================

def get_customer(customer_id: int) -> Dict[str, Any]:
    """Fetch customer by ID."""
    try:
        conn = get_db_connection()
        cur = conn.cursor()

        cur.execute("SELECT * FROM customers WHERE id = ?", (customer_id,))
        row = cur.fetchone()
        conn.close()

        if row:
            return {"success": True, "customer": row_to_dict(row)}
        else:
            return {"success": False, "error": f"Customer {customer_id} not found"}

    except Exception as e:
        return {"success": False, "error": f"Database error: {e}"}


# ============================================================
# REQUIRED MCP TOOL 2 — LIST CUSTOMERS
# ============================================================

def list_customers(status: Optional[str] = None, limit: Optional[int] = 50) -> Dict[str, Any]:
    """List customers optionally filtered by status."""
    try:
        conn = get_db_connection()
        cur = conn.cursor()

        if status:
            if status not in ["active", "disabled"]:
                return {"success": False, "error": "Status must be 'active' or 'disabled'"}
            query = "SELECT * FROM customers WHERE status = ? ORDER BY id LIMIT ?"
            cur.execute(query, (status, limit))
        else:
            query = "SELECT * FROM customers ORDER BY id LIMIT ?"
            cur.execute(query, (limit,))

        rows = cur.fetchall()
        conn.close()

        customers = [row_to_dict(r) for r in rows]
        return {"success": True, "count": len(customers), "customers": customers}

    except Exception as e:
        return {"success": False, "error": f"Database error: {e}"}


# ============================================================
# REQUIRED MCP TOOL 3 — UPDATE CUSTOMER
# ============================================================

def update_customer(customer_id: int, data: Dict[str, Any]) -> Dict[str, Any]:
    """
    Update customer fields using a dynamic dictionary.
    Allowed fields must match the customers table.
    """
    allowed_fields = {"name", "email", "phone", "status"}

    # Filter invalid keys
    updates = {k: v for k, v in data.items() if k in allowed_fields}

    if not updates:
        return {"success": False, "error": "No valid fields to update"}

    try:
        conn = get_db_connection()
        cur = conn.cursor()

        # Check existence
        cur.execute("SELECT * FROM customers WHERE id = ?", (customer_id,))
        if not cur.fetchone():
            conn.close()
            return {"success": False, "error": f"Customer {customer_id} not found"}

        # Build dynamic update query
        fields = ", ".join([f"{k} = ?" for k in updates.keys()])
        params = list(updates.values()) + [customer_id]

        query = f"UPDATE customers SET {fields}, updated_at = CURRENT_TIMESTAMP WHERE id = ?"
        cur.execute(query, params)
        conn.commit()

        # Return updated customer
        cur.execute("SELECT * FROM customers WHERE id = ?", (customer_id,))
        updated = cur.fetchone()
        conn.close()

        return {"success": True, "customer": row_to_dict(updated)}

    except Exception as e:
        return {"success": False, "error": f"Database error: {e}"}


# ============================================================
# REQUIRED MCP TOOL 4 — CREATE TICKET
# ============================================================

def create_ticket(customer_id: int, issue: str, priority: str = "medium") -> Dict[str, Any]:
    """Create a ticket for a customer."""
    if priority not in ["low", "medium", "high"]:
        return {"success": False, "error": "Priority must be low, medium, or high"}

    try:
        conn = get_db_connection()
        cur = conn.cursor()

        # Check customer exists
        cur.execute("SELECT * FROM customers WHERE id = ?", (customer_id,))
        if not cur.fetchone():
            conn.close()
            return {"success": False, "error": f"Customer {customer_id} not found"}

        cur.execute("""
            INSERT INTO tickets (customer_id, issue, priority)
            VALUES (?, ?, ?)
        """, (customer_id, issue, priority))

        ticket_id = cur.lastrowid
        conn.commit()

        # Return created ticket
        cur.execute("SELECT * FROM tickets WHERE id = ?", (ticket_id,))
        row = cur.fetchone()
        conn.close()

        return {"success": True, "ticket": row_to_dict(row)}

    except Exception as e:
        return {"success": False, "error": f"Database error: {e}"}


# ============================================================
#  REQUIRED MCP TOOL 5 — GET CUSTOMER HISTORY
# ============================================================

def get_customer_history(customer_id: int) -> Dict[str, Any]:
    """Return all tickets for a given customer."""
    try:
        conn = get_db_connection()
        cur = conn.cursor()

        # Check customer exists
        cur.execute("SELECT id FROM customers WHERE id = ?", (customer_id,))
        if not cur.fetchone():
            conn.close()
            return {"success": False, "error": f"Customer {customer_id} not found"}

        # Fetch tickets
        cur.execute("SELECT * FROM tickets WHERE customer_id = ? ORDER BY created_at DESC", (customer_id,))
        rows = cur.fetchall()
        conn.close()

        history = [row_to_dict(r) for r in rows]
        return {"success": True, "count": len(history), "tickets": history}

    except Exception as e:
        return {"success": False, "error": f"Database error: {e}"}


# ============================================================
# Quick Sanity Test
# ============================================================

print("MCP Tools loaded!")
print("Available tools:")
print(" - get_customer(customer_id)")
print(" - list_customers(status, limit)")
print(" - update_customer(customer_id, data)")
print(" - create_ticket(customer_id, issue, priority)")
print(" - get_customer_history(customer_id)")

# Quick test
print("\n Quick test - Fetching customer ID 1:")
result = get_customer(1)
if result['success']:
    customer = result['customer']
    print(f"   Name: {customer['name']}")
    print(f"   Email: {customer['email']}")
    print(f"   Status: {customer['status']}")

"""### MCP HTTP Streaming Server Implementation"""

# -----------------------------------------------------------
#                 MCP HTTP SERVER
# -----------------------------------------------------------

from flask import Flask, request, Response, jsonify
from flask_cors import CORS
import json
from typing import Dict, Any

# your DB tool functions must already be defined:
# get_customer()
# list_customers()
# update_customer()
# create_ticket()
# get_customer_history()

# ------------------------------------------
# Flask app
# ------------------------------------------
app = Flask(__name__)
CORS(app)

# ------------------------------------------
# REQUIRED MCP tools metadata
# ------------------------------------------
MCP_TOOLS = [
    {
        "name": "get_customer",
        "description": "Retrieve a specific customer by ID.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "customer_id": {"type": "integer"}
            },
            "required": ["customer_id"]
        }
    },
    {
        "name": "list_customers",
        "description": "List customers, optionally filtered by status.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "status": {"type": "string", "enum": ["active", "disabled"]},
                "limit": {"type": "integer"}
            }
        }
    },
    {
        "name": "update_customer",
        "description": "Update a customer's fields.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "customer_id": {"type": "integer"},
                "data": {"type": "object"}
            },
            "required": ["customer_id", "data"]
        }
    },
    {
        "name": "create_ticket",
        "description": "Create a new support ticket.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "customer_id": {"type": "integer"},
                "issue": {"type": "string"},
                "priority": {"type": "string", "enum": ["low", "medium", "high"]}
            },
            "required": ["customer_id", "issue"]
        }
    },
    {
        "name": "get_customer_history",
        "description": "Retrieve all tickets for a specific customer.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "customer_id": {"type": "integer"}
            },
            "required": ["customer_id"]
        }
    }
]

# ------------------------------------------
# SSE formatter
# ------------------------------------------
def create_sse_message(data: Dict[str, Any]) -> str:
    return "data: " + json.dumps(data) + "\n\n"

# ------------------------------------------
# MCP Handlers
# ------------------------------------------
def handle_initialize(message):
    return {
        "jsonrpc": "2.0",
        "id": message.get("id"),
        "result": {
            "protocolVersion": "2024-11-05",
            "capabilities": {"tools": {}},
            "serverInfo": {
                "name": "customer-mcp-server",
                "version": "1.0.0"
            }
        }
    }

def handle_tools_list(message):
    return {
        "jsonrpc": "2.0",
        "id": message.get("id"),
        "result": {"tools": MCP_TOOLS}
    }

# ------------------------------------------
# Map tool names → actual Python functions
# ------------------------------------------
TOOL_FUNCTIONS = {
    "get_customer": lambda args: get_customer(args["customer_id"]),
    "list_customers": lambda args: list_customers(
        status=args.get("status"),
        limit=args.get("limit", 50)
    ),
    "update_customer": lambda args: update_customer(
        args["customer_id"],
        args["data"]
    ),
    "create_ticket": lambda args: create_ticket(
        args["customer_id"],
        args["issue"],
        args.get("priority", "medium")
    ),
    "get_customer_history": lambda args: get_customer_history(
        args["customer_id"]
    ),
}

# ------------------------------------------
# Handle tool calls
# ------------------------------------------
def handle_tools_call(message):
    params = message.get("params", {})
    tool_name = params.get("name")
    arguments = params.get("arguments", {})

    if tool_name not in TOOL_FUNCTIONS:
        return {
            "jsonrpc": "2.0",
            "id": message.get("id"),
            "error": {
                "code": -32601,
                "message": f"Tool not found: {tool_name}"
            }
        }

    try:
        result = TOOL_FUNCTIONS[tool_name](arguments)

        return {
            "jsonrpc": "2.0",
            "id": message.get("id"),
            "result": {
                "content": [
                    {"type": "json", "json": result}
                ]
            }
        }

    except Exception as e:
        return {
            "jsonrpc": "2.0",
            "id": message.get("id"),
            "error": {
                "code": -32603,
                "message": f"Execution error: {str(e)}"
            }
        }

# ------------------------------------------
# Route message → handler
# ------------------------------------------
def process_mcp_message(message):
    method = message.get("method")

    if method == "initialize":
        return handle_initialize(message)
    elif method == "tools/list":
        return handle_tools_list(message)
    elif method == "tools/call":
        return handle_tools_call(message)
    else:
        return {
            "jsonrpc": "2.0",
            "id": message.get("id"),
            "error": {
                "code": -32601,
                "message": f"Unknown method: {method}"
            }
        }

# ------------------------------------------
# MCP Endpoint (SSE streaming)
# ------------------------------------------
@app.route('/mcp', methods=['POST'])
def mcp_endpoint():
    message = request.get_json()

    def generate():
        try:
            response = process_mcp_message(message)
            yield create_sse_message(response)
        except Exception as e:
            yield create_sse_message({
                "jsonrpc": "2.0",
                "id": None,
                "error": {"code": -32700, "message": str(e)}
            })

    return Response(generate(), mimetype='text/event-stream')

@app.route('/health', methods=['GET'])
def health():
    return jsonify({"status": "healthy", "server": "customer-mcp-server"})

print("Corrected MCP Server loaded with required tools.")

"""###Start the MCP Server"""

# ======================================================
#   CLEAN AND CORRECT MCP SERVER STARTER (Flask + Ngrok)
# ======================================================

import threading
import time
import requests
from termcolor import colored
from pyngrok import ngrok
from google.colab import userdata

SERVER_HOST = "127.0.0.1"
SERVER_PORT = 5000
SERVER_URL = f"http://{SERVER_HOST}:{SERVER_PORT}"

server_thread = None
server_running = False


def run_server():
    """Run the Flask MCP server in a background thread."""
    global server_running
    server_running = True
    print(colored("MCP server is starting...", "blue"))
    app.run(host=SERVER_HOST, port=SERVER_PORT, debug=False, use_reloader=False)


def start_server(use_ngrok=True):
    """Start Flask MCP Server + optional Ngrok tunnel."""
    global server_thread, server_running

    # Avoid duplicate servers
    if server_thread and server_thread.is_alive():
        print(colored("Server is already running.", "yellow"))
        return

    print(colored("Launching MCP Server...", "cyan"))
    server_thread = threading.Thread(target=run_server, daemon=True)
    server_thread.start()

    # Give Flask time to start
    time.sleep(2)

    # Check if it started successfully
    try:
        response = requests.get(f"{SERVER_URL}/health", timeout=5)
        if response.status_code == 200:
            print(colored("MCP Server is live!", "green"))
            print(colored(f"Local Endpoint: {SERVER_URL}/mcp", "cyan"))
            print(colored(f"Health Check: {SERVER_URL}/health", "cyan"))
        else:
            print(colored("Server is running but health check failed", "red"))
            return
    except Exception as e:
        print(colored(f"Cannot connect to server: {e}", "red"))
        return

    # ----- Optional NGROK Tunnel -----
    if not use_ngrok:
        print(colored("Ngrok disabled — using local server only.", "yellow"))
        return

    print(colored("\nSetting up Ngrok public tunnel...", "cyan"))
    try:
        # Authenticate ngrok
        try:
            authtoken = userdata.get("NGROK_AUTHTOKEN")
            ngrok.set_auth_token(authtoken)
            print(colored(" Ngrok authenticated", "green"))
        except Exception:
            print(colored("Ngrok token missing. Local server only.", "yellow"))
            print(colored(f"Local MCP URL: {SERVER_URL}/mcp", "cyan"))
            return

        # Create HTTP tunnel
        public_url = ngrok.connect(SERVER_PORT)
        print(colored(f"Public URL: {public_url}", "green", attrs=["bold"]))
        print(colored(f"MCP Endpoint: {public_url}/mcp", "green"))
        print(colored(f"Health: {public_url}/health", "cyan"))

        print("\n🔍 MCP Inspector Instructions:")
        print(colored("1. Install MCP Inspector: npm i -g @modelcontextprotocol/inspector", "yellow"))
        print(colored("2. Run: npx @modelcontextprotocol/inspector", "yellow"))
        print(colored(f"3. Connect to MCP URL: {public_url}/mcp", "yellow"))
        print(colored("4. Test your customer management tools!", "yellow"))

    except Exception as e:
        print(colored(f"Ngrok failed: {e}", "yellow"))
        print(colored("Using local server only.", "yellow"))


def stop_server():
    """Stop the server safely (works in Colab)."""
    global server_running
    server_running = False
    print(colored("MCP server stopped (thread will persist until runtime reset)", "yellow"))


def check_server_status():
    """Verify if the server is healthy."""
    try:
        response = requests.get(f"{SERVER_URL}/health", timeout=2)
        if response.status_code == 200:
            data = response.json()
            print(colored("Server is healthy", "green"))
            print(json.dumps(data, indent=2))
            return True
        else:
            print(colored("Server responded incorrectly", "red"))
            return False
    except Exception as e:
        print(colored(" Server is not reachable", "red"))
        print("Error:", e)
        return False


# Auto-start server
start_server()

"""###MCP Testing"""

import requests
import json
from termcolor import colored

def send_mcp_message(method: str, params: dict = None, message_id: int = 1):
    """
    Send an MCP message to the server (via SSE) and parse the response.
    """
    message = {
        "jsonrpc": "2.0",
        "id": message_id,
        "method": method
    }
    if params:
        message["params"] = params

    print(colored("\n📤 Sending MCP Request:", "cyan", attrs=["bold"]))
    print(colored(json.dumps(message, indent=2), "cyan"))

    try:
        response = requests.post(
            f"{SERVER_URL}/mcp",
            json=message,
            stream=True,
            timeout=10
        )

        for line in response.iter_lines():
            if not line:
                continue

            line = line.decode("utf-8")
            if line.startswith("data: "):
                payload = json.loads(line[6:])  # remove 'data:'

                print(colored("\n📥 Received MCP Response:", "green", attrs=["bold"]))
                print(colored(json.dumps(payload, indent=2), "green"))
                return payload

    except Exception as e:
        print(colored(f"\n Error: {e}", "red"))
        return None

print(colored("="*60, "magenta"))
print(colored("TEST 1: MCP INITIALIZATION", "magenta", attrs=["bold"]))
print(colored("="*60, "magenta"))

init_response = send_mcp_message(
    method="initialize",
    params={
        "protocolVersion": "2024-11-05",
        "capabilities": {},
        "clientInfo": {"name": "colab-test-client", "version": "1.0.0"},
    },
    message_id=1
)

if init_response and "result" in init_response:
    print(colored("\n Initialization successful!", "green", attrs=["bold"]))
    print("Protocol Version:", init_response["result"]["protocolVersion"])
    print("Server:", init_response["result"]["serverInfo"]["name"])
else:
    print(colored("\n Initialization failed", "red", attrs=["bold"]))

"""### List Available Tools"""

print(colored("="*60, "magenta"))
print(colored("TEST 2: LIST AVAILABLE TOOLS", "magenta", attrs=["bold"]))
print(colored("="*60, "magenta"))

tools_response = send_mcp_message(
    method="tools/list",
    message_id=2
)

if tools_response and "result" in tools_response:
    tools = tools_response["result"]["tools"]
    print(colored(f"\nFound {len(tools)} tools:", "green", attrs=["bold"]))
    for i, tool in enumerate(tools, start=1):
        print(colored(f"\n{i}. {tool['name']}", "yellow", attrs=["bold"]))
        print("   " + tool["description"])
else:
    print(colored("\nFailed to list tools", "red"))

"""###Call Tool: Get A Customer"""

print(colored("="*60, "blue"))
print(colored("TEST: get_customer(customer_id)", "blue", attrs=["bold"]))
print(colored("="*60, "blue"))

response = send_mcp_message(
    method="tools/call",
    params={
        "name": "get_customer",
        "arguments": {"customer_id": 1}
    },
    message_id=101
)

try:
    result = response["result"]["content"][0]["json"]
except:
    result = None

print(colored("\n Result:", "cyan"))
print(json.dumps(result, indent=2))

if result and result.get("success"):
    print(colored("\n Customer found!", "green", attrs=["bold"]))
else:
    print(colored("\n Customer not found", "red"))

"""###Call Tool: List All Customers"""

print(colored("="*60, "magenta"))
print(colored("TEST 3: LIST ALL CUSTOMERS", "magenta", attrs=["bold"]))
print(colored("="*60, "magenta"))

list_response = send_mcp_message(
    method="tools/call",
    params={
        "name": "list_customers",
        "arguments": {}
    },
    message_id=3
)

# Correct extraction of MCP JSON result
try:
    content = list_response["result"]["content"][0]
    result_json = content["json"]   # <-- NEW (correct)
except:
    print(colored("\n Failed to parse tool response", "red"))
    result_json = None

if result_json and result_json.get("success"):
    print(colored(f"\n {result_json['count']} customers found:", "green", attrs=["bold"]))

    for cust in result_json["customers"]:
        color = "green" if cust["status"] == "active" else "red"
        print(f"\nID: {cust['id']}")
        print(f"   Name: {cust['name']}")
        print(f"   Email: {cust['email']}")
        print(f"   Phone: {cust['phone']}")
        print(colored(f"   Status: {cust['status']}", color))
else:
    print(colored("\n list_customers failed", "red"))

"""###Call Tool: Get A Customer's History"""

print(colored("="*60, "magenta"))
print(colored("TEST: get_customer_history(customer_id)", "magenta", attrs=["bold"]))
print(colored("="*60, "magenta"))

response = send_mcp_message(
    method="tools/call",
    params={
        "name": "get_customer_history",
        "arguments": {"customer_id": 1}
    },
    message_id=104
)

try:
    result = response["result"]["content"][0]["json"]
except:
    result = None

print(colored("\n Result:", "cyan"))
print(json.dumps(result, indent=2))

if result and result.get("success"):
    print(colored(f"\n Found {result['count']} tickets!", "green", attrs=["bold"]))
else:
    print(colored("\n No ticket history found", "red"))

"""###Testing with MCP Inspector"""

# Check server status
check_server_status()

"""# A2A Coordination"""

!pip install --upgrade -q google-genai google-adk==1.9.0 a2a-sdk==0.3.0 python-dotenv aiohttp uvicorn requests mermaid-python nest-asyncio

"""###Configuration"""

import sys

from a2a.client import client as real_client_module
from a2a.client.card_resolver import A2ACardResolver


class PatchedClientModule:
    def __init__(self, real_module) -> None:
        for attr in dir(real_module):
            if not attr.startswith('_'):
                setattr(self, attr, getattr(real_module, attr))
        self.A2ACardResolver = A2ACardResolver


patched_module = PatchedClientModule(real_client_module)
sys.modules['a2a.client.client'] = patched_module  # type: ignore

import asyncio
import logging
import os
import sys
import threading
import time

from typing import Any

import httpx
import nest_asyncio
import uvicorn

from a2a.client import ClientConfig, ClientFactory, create_text_message_object
from a2a.server.apps import A2AStarletteApplication
from a2a.server.request_handlers import DefaultRequestHandler
from a2a.server.tasks import InMemoryTaskStore
from a2a.types import (
    AgentCapabilities,
    AgentCard,
    AgentSkill,
    TransportProtocol,
)
from a2a.utils.constants import AGENT_CARD_WELL_KNOWN_PATH
from dotenv import load_dotenv
from google.adk.a2a.executor.a2a_agent_executor import (
    A2aAgentExecutor,
    A2aAgentExecutorConfig,
)
from google.adk.agents import Agent, SequentialAgent
from google.adk.agents.remote_a2a_agent import RemoteA2aAgent
from google.adk.artifacts import InMemoryArtifactService
from google.adk.memory.in_memory_memory_service import InMemoryMemoryService
from google.adk.runners import Runner
from google.adk.sessions import InMemorySessionService
from google.adk.tools import google_search

# Set Google Cloud Configuration
os.environ['GOOGLE_GENAI_USE_VERTEXAI'] = 'FALSE'
os.environ['GOOGLE_CLOUD_PROJECT'] = (
    'gen-lang-client-0113096660'
)
os.environ['GOOGLE_CLOUD_LOCATION'] = (
    'us-central1'  # Replace with your location
)

load_dotenv()
from google.colab import userdata
os.environ['GOOGLE_API_KEY'] = userdata.get('GEMINI_API_KEY')

print('Environment variables configured:')
print(f'GOOGLE_GENAI_USE_VERTEXAI: {os.environ["GOOGLE_GENAI_USE_VERTEXAI"]}')
print(f'GOOGLE_CLOUD_PROJECT: {os.environ["GOOGLE_CLOUD_PROJECT"]}')
print(f'GOOGLE_CLOUD_LOCATION: {os.environ["GOOGLE_CLOUD_LOCATION"]}')

# Authenticate your notebook environment (Colab only)
if 'google.colab' in sys.modules:
    from google.colab import auth

    auth.authenticate_user(project_id=os.environ['GOOGLE_CLOUD_PROJECT'])

# Setup logging
logging.basicConfig(
    level=logging.ERROR,
    format='%(asctime)s - %(levelname)s - %(name)s - %(message)s',
)

"""#Building A2A System

###gent 1: Customer Data Agent (Specialist)
"""

# Create the Trending Topics ADK Agent
customer_data_agent = Agent(
    model='gemini-2.5-pro',
    name='customer_data_agent',
    instruction="""
    You are the Customer Data Agent.

    Your responsibilities:
    - Fetch customer information (get_customer)
    - List all or filtered customers (list_customers)
    - Update customer records (update_customer)
    - Create support tickets (create_ticket)
    - Retrieve a customer's ticket history (get_customer_history)

    When the user asks for ANY data-related action, YOU MUST:
    1. Select the correct MCP tool.
    2. Construct the appropriate input object.
    3. Call the MCP server through mcp_call(tool_name, arguments).
    4. Return ONLY the JSON object produced by the MCP tool.
    5. Never add additional commentary unless asked.

    Examples:
    - "Show me customer 5"  → call get_customer
    - "List disabled customers" → call list_customers(status="disabled")
    - "Update customer's email" → update_customer
    - "Create a support ticket" → create_ticket
    - "Show history for customer 2" → get_customer_history

    Return ONLY JSON, no extra text.
    """,
    tools=[
        get_customer,
        list_customers,
        update_customer,
        create_ticket,
        get_customer_history
    ]
)

print("Customer Data Agent created.")

customer_data_agent_card = AgentCard(
    name='Customer Data Agent',
    url='http://localhost:9101',
    description='Provides customer database operations using MCP tools',
    version='1.0',
    capabilities=AgentCapabilities(streaming=True),
    default_input_modes=['text/plain'],
    default_output_modes=['text/plain'],
    preferred_transport=TransportProtocol.jsonrpc,
    skills=[
        AgentSkill(
            id='customer_database_access',
            name='Customer Database Operations',
            description=(
                'Retrieve, update, and manage customer records using MCP tools. '
                'Supports customer lookup, updates, ticket creation, and '
                'ticket history retrieval.'
            ),
            tags=['database', 'customer', 'records', 'support', 'MCP'],
            examples=[
                "Get customer 3",
                "List active customers",
                "Update customer 10 email",
                "Create ticket for customer 5",
                "Show ticket history for customer 1"
            ],
        )
    ],
)

print("Customer Data AgentCard created.")

customer_data_agent_remote = RemoteA2aAgent(
    name="customer_data_agent_remote",
    description="Remote connector to Customer Data Agent via A2A",
    agent_card="http://localhost:9101" + AGENT_CARD_WELL_KNOWN_PATH,
)

print("Remote Customer Data Agent created.")

"""###Agent 2: Support Agent (Specialist)"""

# Create the Trending Topics ADK Agent
support_agent = Agent(
    model='gemini-2.5-pro',
    name='support_agent',
    instruction="""
    You are the Support Agent.

    Your role:
    - Answer general customer support questions.
    - When needed, request customer information from the Customer Data Agent.
    - When issue is complex, escalate by creating a ticket via Customer Data Agent.
    - Always use remote_customer_data_agent for customer info:
        • get_customer
        • list_customers
        • update_customer
        • create_ticket
        • get_customer_history

    Rules:
    1. If the user mentions a customer ID, ALWAYS fetch that customer's info first.
    2. If user asks for updating profile → call update_customer through the customer data agent.
    3. If the user reports a problem → create a ticket.
    4. Always return final answer in natural human-friendly text.
    5. If data is needed, you MUST call the customer_data_agent via:
          remote_customer_data_agent.run(task)
    6. Never hallucinate customer details — always read from the MCP DB.

    Examples of behavior:

    User: "Customer 3 says their email is wrong."
    → Fetch customer 3 → update_customer → respond

    User: "Customer 5 cannot log in."
    → Fetch customer 5 → create_ticket(priority="high") → respond

    User: "Show me customer 2 history."
    → get_customer_history → summarize and reply.

    """,
    tools=[
        get_customer,
        list_customers,
        update_customer,
        create_ticket,
        get_customer_history
    ]
)

print("Support Agent created.")

support_agent_card = AgentCard(
    name='Support Agent',
    url='http://localhost:9102',
    description='Handles customer support queries and delegates data operations to the Customer Data Agent.',
    version='1.0',
    capabilities=AgentCapabilities(streaming=True),
    default_input_modes=['text/plain'],
    default_output_modes=['text/plain'],
    preferred_transport=TransportProtocol.jsonrpc,
    skills=[
        AgentSkill(
            id='customer_support_handling',
            name='Customer Support Handling',
            description=(
                'Resolves general customer support issues, checks customer identity, '
                'requests data from the Customer Data Agent, and escalates issues '
                'by creating tickets when needed.'
            ),
            tags=['support', 'helpdesk', 'customer service', 'escalation'],
            examples=[
                "Help customer 3 reset their email.",
                "Customer 5 cannot login, what should we do?",
                "Explain the account status for customer 7.",
                "File a support request for customer 2.",
                "Summarize the ticket history for customer 1."
            ],
        )
    ],
)

print("Support Agent Card created.")

support_agent_remote = RemoteA2aAgent(
    name="support_agent_remote",
    description="Remote access to Support Agent via A2A",
    agent_card="http://localhost:9102" + AGENT_CARD_WELL_KNOWN_PATH,
)

print("Remote Support Agent created.")

"""###Agent 3: Router Agent (Orchestrator)"""

router_agent = Agent(
    model="gemini-2.5-pro",
    name="router_agent",
    instruction="""
    You are the Router Agent in a multi-agent customer service system.

    Your responsibilities:
    1. Receive customer queries.
    2. Detect user intents (customer lookup, account issues, billing, profile updates,
       ticket creation, multi-intent requests).
    3. Use the appropriate MCP-backed tools to interact with the customer database.
    4. For multi-step or multi-intent queries, call multiple tools and merge the results.
    5. NEVER hallucinate customer data — always use tools to read/write from the DB.

    Available tools (IMPORTANT):
    - get_customer(customer_id: int)
        → Fetch a single customer's full record.
    - list_customers(status: Optional['active'|'disabled'], limit: int = 50)
        → List customers, optionally filtered by status.
    - update_customer(customer_id: int, data: dict)
        → Update customer fields such as email, phone, or status.
    - create_ticket(customer_id: int, issue: str, priority: 'low'|'medium'|'high' = 'medium')
        → Create a support ticket for a customer.
    - get_customer_history(customer_id: int)
        → Get all tickets for a given customer.

    Routing rules:
    - If the user asks for a specific customer by ID → use get_customer.
    - If the user wants a list of customers (e.g., all active) → use list_customers.
    - If the user wants to change profile details → use update_customer and then
      confirm the updated fields.
    - If the user reports a problem or incident → use create_ticket (priority 'high'
      for urgent issues like billing problems and refunds).
    - If the user asks for their ticket history → use get_customer_history.
    - For complex queries (e.g., "all active customers who have open tickets"),
      you may need multiple tool calls:
        • First list active customers
        • Then get ticket histories and filter for open tickets.

    Your output:
    - Provide a clean, human-friendly response summarizing the results of your tool calls.
    - When helpful, you may include key fields (e.g., name, email, status, ticket status).
    """,
    tools=[
        get_customer,
        list_customers,
        update_customer,
        create_ticket,
        get_customer_history,
    ],
)

print("Router Agent created.")


router_agent_card = AgentCard(
    name="Router Agent",
    url="http://localhost:9200",
    description=(
        "The central orchestrator of the multi-agent customer service system. "
        "Routes tasks between the Customer Data Agent and Support Agent using intent analysis. "
        "Handles multi-step workflows, escalation, and coordinated agent calls."
    ),
    version="1.0",
    capabilities=AgentCapabilities(streaming=True),
    default_input_modes=["text/plain"],
    default_output_modes=["text/plain"],
    preferred_transport=TransportProtocol.jsonrpc,
    skills=[
        AgentSkill(
            id="intent_routing",
            name="Intent Routing & Multi-Agent Orchestration",
            description=(
                "Understands customer queries, identifies intent, and routes requests "
                "to the correct specialist agent. Supports multi-step workflows and "
                "merging results from multiple agents."
            ),
            tags=["router", "orchestration", "multi-agent", "customer", "support"],
            examples=[
                "Get customer information for ID 5",
                "Help customer 12—they can't log in",
                "Update customer 7 email to [email protected]",
                "Show open tickets for customer 4",
                "List all disabled customers",
                "Create a ticket for customer 3",
                "I was double charged—help me",
            ],
        )
    ],
)

print("Router Agent Card created.")

"""###Starting the A2A Servers"""

def create_agent_a2a_server(agent, agent_card):
    """Create an A2A server for any ADK agent.

    Args:
        agent: The ADK agent instance
        agent_card: The ADK agent card

    Returns:
        A2AStarletteApplication instance
    """
    runner = Runner(
        app_name=agent.name,
        agent=agent,
        artifact_service=InMemoryArtifactService(),
        session_service=InMemorySessionService(),
        memory_service=InMemoryMemoryService(),
    )

    config = A2aAgentExecutorConfig()
    executor = A2aAgentExecutor(runner=runner, config=config)

    request_handler = DefaultRequestHandler(
        agent_executor=executor,
        task_store=InMemoryTaskStore(),
    )

    # Create A2A application
    return A2AStarletteApplication(
        agent_card=agent_card, http_handler=request_handler
    )

# Apply nest_asyncio
nest_asyncio.apply()

# Store server tasks
server_tasks: list[asyncio.Task] = []


async def run_agent_server(agent, agent_card, port) -> None:
    """Run a single agent server."""
    app = create_agent_a2a_server(agent, agent_card)

    config = uvicorn.Config(
        app.build(),
        host='127.0.0.1',
        port=port,
        log_level='warning',
        loop='none',  # IMPORTANT for running inside Colab
    )

    server = uvicorn.Server(config)
    await server.serve()


async def start_all_servers() -> None:
    """
    Start Customer Data Agent, Support Agent, and Router Agent
    in the same event loop.
    """
    tasks = [
        asyncio.create_task(
            run_agent_server(customer_data_agent, customer_data_agent_card, 9101)
        ),
        asyncio.create_task(
            run_agent_server(support_agent, support_agent_card, 9102)
        ),
        asyncio.create_task(
            run_agent_server(router_agent, router_agent_card, 9200)
        ),
    ]

    # Allow servers time to boot
    await asyncio.sleep(2)

    print('All agent servers started successfully!')
    print('   - Customer Data Agent: http://127.0.0.1:9101')
    print('   - Support Agent:       http://127.0.0.1:9102')
    print('   - Router Agent:        http://127.0.0.1:9200')

    # Keep servers alive
    try:
        await asyncio.gather(*tasks)
    except KeyboardInterrupt:
        print('Shutting down servers...')


def run_servers_in_background() -> None:
    """
    Run everything in a background thread so Colab doesn't block.
    """
    loop = asyncio.new_event_loop()
    asyncio.set_event_loop(loop)
    loop.run_until_complete(start_all_servers())


# Launch servers in a background daemon thread
server_thread = threading.Thread(target=run_servers_in_background, daemon=True)
server_thread.start()

# Wait for boot
time.sleep(3)

print("Customer Data Agent Card:")
print(customer_data_agent_card)

print("\nSupport Agent Card:")
print(support_agent_card)

print("\nRouter Agent Card:")
print(router_agent_card)

"""###Testing the A2A System"""

class A2ASimpleClient:
    """A2A Simple to call A2A servers."""

    def __init__(self, default_timeout: float = 240.0):
        self._agent_info_cache: dict[
            str, dict[str, Any] | None
        ] = {}  # Cache for agent metadata
        self.default_timeout = default_timeout

    async def create_task(self, agent_url: str, message: str) -> str:
        """Send a message to an A2A agent and return a safe text response."""
        timeout_config = httpx.Timeout(
            timeout=self.default_timeout,
            connect=10.0,
            read=self.default_timeout,
            write=10.0,
            pool=5.0,
        )

        async with httpx.AsyncClient(timeout=timeout_config) as httpx_client:
            # Fetch or reuse agent card
            if agent_url in self._agent_info_cache and self._agent_info_cache[agent_url] is not None:
                agent_card_data = self._agent_info_cache[agent_url]
            else:
                agent_card_response = await httpx_client.get(
                    f"{agent_url}{AGENT_CARD_WELL_KNOWN_PATH}"
                )
                agent_card_data = agent_card_response.json()
                self._agent_info_cache[agent_url] = agent_card_data

            agent_card = AgentCard(**agent_card_data)

            config = ClientConfig(
                httpx_client=httpx_client,
                supported_transports=[
                    TransportProtocol.jsonrpc,
                    TransportProtocol.http_json,
                ],
                use_client_preference=True,
            )

            factory = ClientFactory(config)
            client = factory.create(agent_card)

            message_obj = create_text_message_object(content=message)

            responses = []
            async for response in client.send_message(message_obj):
                responses.append(response)

            if not responses:
                return "No response received (empty responses list)."

            first = responses[0]
            if not (isinstance(first, tuple) and len(first) > 0):
                return f"Unexpected response shape: {first}"

            task = first[0]

            # 1) If the task has an error field, surface it
            if getattr(task, "error", None) is not None:
                return f"Task error from agent: {task.error}"

            # 2) Try artifacts first (happy path)
            try:
                artifacts = getattr(task, "artifacts", None)
                if artifacts and len(artifacts) > 0:
                    parts = getattr(artifacts[0], "parts", None)
                    if parts and len(parts) > 0:
                        root = getattr(parts[0], "root", None)
                        text = getattr(root, "text", None)
                        if text:
                            return text
            except Exception:
                # Ignore and fall through to history-based extraction
                pass

            # 3) Fallback: look at the last message in task.history
            history = getattr(task, "history", []) or []
            if history:
                last_msg = history[-1]
                parts = getattr(last_msg, "parts", None)
                if parts and len(parts) > 0:
                    root = getattr(parts[0], "root", None)
                    text = getattr(root, "text", None)
                    if text:
                        return text

            # 4) Final fallback: dump the task
            return f"Task completed but no text found.\nRaw task: {task!r}"

a2a_client = A2ASimpleClient()

"""##A2A Scenarios

###Scenario 1
"""

async def test_scenario_1_task_allocation() -> None:
    """Scenario 1: Task Allocation."""
    response = await a2a_client.create_task(
        'http://localhost:9200',
        "I need help with my account, customer ID 12345"
    )
    print(response)

# Run
asyncio.run(test_scenario_1_task_allocation())

"""###Scenario 2"""

async def test_scenario_2_negotiation() -> None:
    """Scenario 2: Negotiation and Escalation."""
    response = await a2a_client.create_task(
        'http://localhost:9200',
        "I want to cancel my subscription but I'm having billing issues"
    )
    print(response)

# Run
asyncio.run(test_scenario_2_negotiation())

"""###Scenario 3"""

async def test_scenario_3_multistep() -> None:
    """Scenario 3: Multi-step coordination."""
    response = await a2a_client.create_task(
        'http://localhost:9200',
        "What's the status of all high-priority tickets for premium customers?"
    )
    print(response)

# Run
asyncio.run(test_scenario_3_multistep())

"""# Test Scenarios

###Coordinated Query: "I'm customer 12345 and need help upgrading my account"
"""

async def test_coordinated_query() -> None:
    """Test: Coordinated query with data fetch + support handling."""
    response = await a2a_client.create_task(
        'http://localhost:9200',
        "I'm customer 12345 and need help upgrading my account"
    )
    print(response)

# Run
asyncio.run(test_coordinated_query())

"""###Escalation: "I've been charged twice, please refund immediately!"
"""

async def test_escalation_query() -> None:
    """Test: Urgent escalation scenario."""
    response = await a2a_client.create_task(
        'http://localhost:9200',
        "I've been charged twice, please refund immediately!"
    )
    print(response)

# Run
asyncio.run(test_escalation_query())

"""### Multi-Intent: "Update my email to new@email.com and show my ticket history"
"""

async def test_multi_intent_query() -> None:
    """Test: Multi-intent query (update email + show ticket history)."""
    response = await a2a_client.create_task(
        'http://localhost:9200',
        "My customer ID is 5. Update my email to [email protected] and then show my ticket history."
    )
    print(response)

# Run
asyncio.run(test_multi_intent_query())

"""###Complex Query (Requires cross-agent reasoning)"""

async def test_complex_query() -> None:
    """Test: Complex query requiring multi-agent reasoning."""
    response = await a2a_client.create_task(
        'http://localhost:9200',
        "Show me all active customers who have open tickets."
    )
    print(response)

# Run
asyncio.run(test_complex_query())

"""# Conclusion

This project helped me understand how to build a complete multi-agent system using A2A communication and the Model Context Protocol. I learned how different agents can specialize in distinct tasks, such as routing, data access, and customer support, while still working together as an integrated system. Implementing MCP tools gave me a clear understanding of how structured operations like customer lookup, updates, and ticket creation can be exposed to an LLM in a safe and controllable way. Working with A2A servers also taught me how agents advertise their capabilities through agent cards and exchange messages in a predictable and inspectable format. Overall, this project showed me how modern GenAI systems combine tool execution, reasoning, and orchestration into one workflow.

The main challenges came from aligning agent instructions with their declared capabilities. Early in development, the Router Agent repeatedly produced errors because the LLM attempted tool calls that the agent had not been allowed to use. Solving this required adjusting both the prompt and the registered tools so the agent could reason and execute actions correctly. I also encountered difficulties running several servers in Colab and extracting meaningful responses when runs failed. These issues taught me the importance of debugging protocols, validating assumptions at each step, and designing robust error handling for multi-agent systems.
"""